(WIP) Extend the ixfr-out test to  actually verify produced output.
Currently fails due to an unrelated TSIG bug causing dig to fail.

diff --git a/integration-tests/tests/ixfr-out/action.yml b/integration-tests/tests/ixfr-out/action.yml
--- a/integration-tests/tests/ixfr-out/action.yml
+++ b/integration-tests/tests/ixfr-out/action.yml
@@ -29,21 +29,7 @@ runs:
     - uses: ./.github/actions/setup-and-start-cascade
       with:
         log-level: ${{ inputs.log-level }}
-
-    - name: Add a NOTIFY with TSIG outbound policy
-      run: |
-        POLICY_DIR=$(integration-tests/scripts/get-default-path.sh policy-dir)
-        cascade template policy | grep -Ev '(send-notify-to|accept-xfr-from)' > "${POLICY_DIR}/without-tsig.toml"
-        cascade template policy | grep -Ev '(send-notify-to|accept-xfr-from)' > "${POLICY_DIR}/with-tsig.toml"
-
-        sed -i -e 's/serial-policy = "date-counter"/serial-policy = "keep"/' "${POLICY_DIR}/without-tsig.toml"
-        sed -i -e 's/serial-policy = "date-counter"/serial-policy = "keep"/' "${POLICY_DIR}/with-tsig.toml"
-      
-        echo 'send-notify-to = ["127.0.0.1:1054"]' >> "${POLICY_DIR}/without-tsig.toml"
-        echo 'send-notify-to = ["127.0.0.1:1054^tsig-key"]' >> "${POLICY_DIR}/with-tsig.toml"
-
-        cascade tsig add tsig-key hmac-sha256 "COzoVsYQmXeXiyq1Quhp0bbVnMyxjPxsaGSoIWR98i0="
-        cascade policy reload
+        fake-time: 1600000000
   
     - name: Determine the downstrem secondary zone config to use
       id: set-vars
@@ -51,19 +37,35 @@ runs:
         if [[ "${{ inputs.with-tsig }}" == "true" ]]; then
           ZONE_NAME="notify-and-xfr-tsig.test."
           POLICY_NAME="with-tsig"
+          KEY_NAME="Knotify-and-xfr-tsig.test.+015+10995.key"
         else
           ZONE_NAME="example.test."
           POLICY_NAME="without-tsig"
+          KEY_NAME="Kexample.test.+015+00580.key"
         fi
         echo "ZONE_NAME=${ZONE_NAME}" >> "$GITHUB_OUTPUT"
         echo "POLICY_NAME=${POLICY_NAME}" >> "$GITHUB_OUTPUT"
+        echo "KEY_NAME=${KEY_NAME}" >> "$GITHUB_OUTPUT"
+        echo "TSIG_SPEC=hmac-sha256:tsig-key:COzoVsYQmXeXiyq1Quhp0bbVnMyxjPxsaGSoIWR98i0=" >> "$GITHUB_OUTPUT"
+
+    - name: Add the TSIG key
+      if: ${{ inputs.with-tsig }}
+      run: |
+        cascade tsig add ${{ steps.set-vars.outputs.TSIG_SPEC }}
+
+    - name: Add policy ${{ steps.set-vars.outputs.POLICY_NAME }} and reload
+      run: |
+        POLICY_DIR=$(integration-tests/scripts/get-default-path.sh policy-dir)
+        TEST_DIR="${PWD}/integration-tests/ixfr-out"
+        cp "${TEST_DIR}/policies/${{ steps.set-vars.outputs.POLICY_NAME }}.toml" "${POLICY_DIR}/"
+        cascade policy reload
 
     # The zone name has to match a zone configured in the downstream NSD
     # nameserver. Zone 'notify-and-xfr-tsig.test' is a zone in the downstream
     # NSD nameserver that is configured to expect TSIG to be used for the
     # NOTIFY message it is sent, to use IXFR (as opposed to only AXFR) and for
     # it to need to use TSIG to request an IXFR transfer from Cascade.
-    - name: Make an initial zone based on RFC 1995 section 7
+    - name: Make a ${{ steps.set-vars.outputs.ZONE_NAME }} zone based on RFC 1995 section 7
       env:
         ZONE_NAME: ${{ steps.set-vars.outputs.ZONE_NAME }}
       run: |
@@ -75,14 +77,19 @@ runs:
         NEZU.${ZONE_NAME}  IN A   133.69.136.5
         EOF
 
-    - name: Add the zone using the custom policy
+    - name: Add the ${{ steps.set-vars.outputs.ZONE_NAME }} zone using policy ${{ steps.set-vars.outputs.POLICY_NAME }}
       env:
         ZONE_NAME: ${{ steps.set-vars.outputs.ZONE_NAME }}
         POLICY_NAME: ${{ steps.set-vars.outputs.POLICY_NAME }}
+        KEY_NAME: ${{ steps.set-vars.outputs.KEY_NAME }}
       run: |
-        cascade zone add --policy ${POLICY_NAME} --source "${ZONE_NAME}zone" ${ZONE_NAME}
+        TEST_DIR="${PWD}/integration-tests/ixfr-out"
+        KEY_FILE="${TEST_DIR}/keys/${KEY_NAME}"
+        # Use a pre-created key so that generated signatures can be matched
+        # against reference output.
+        cascade zone add --policy ${POLICY_NAME} --source "${ZONE_NAME}zone" --import-csk-file "${KEY_FILE}" ${ZONE_NAME}
 
-    - name: Check zone status
+    - name: Check zone ${{ steps.set-vars.outputs.ZONE_NAME }} status
       env:
         ZONE_NAME: ${{ steps.set-vars.outputs.ZONE_NAME }}
       run: |
@@ -97,7 +104,7 @@ runs:
           sleep 1
         done
 
-    - name: Check the SOA SERIAL at the NSD secondary
+    - name: Expect serial 1 of zone ${{ steps.set-vars.outputs.ZONE_NAME }} at the NSD secondary
       env:
         ZONE_NAME: ${{ steps.set-vars.outputs.ZONE_NAME }}
       run: |
@@ -113,21 +120,21 @@ runs:
           sleep 1
         done
 
-    - name: Edit the source zone and tell Cascade to reload it.
+    - name: Edit and reload serial 2 of zone ${{ steps.set-vars.outputs.ZONE_NAME }}
       env:
         ZONE_NAME: ${{ steps.set-vars.outputs.ZONE_NAME }}
       run: |
         cat >"${ZONE_NAME}zone" <<EOF
         ${ZONE_NAME}          IN SOA ns.${ZONE_NAME} mail.${ZONE_NAME} (
                                      2 60 60 3600 5)
-                               IN NS  NS.${ZONE_NAME}
+                              IN NS  NS.${ZONE_NAME}
         NS.${ZONE_NAME}       IN A   133.69.136.1
         JAIN-BB.${ZONE_NAME}  IN A   133.69.136.4
-                               IN A   192.41.197.2
+                              IN A   192.41.197.2
         EOF
         cascade zone reload ${ZONE_NAME}
 
-    - name: Check zone status
+    - name: Check zone ${{ steps.set-vars.outputs.ZONE_NAME }} status after reload
       env:
         ZONE_NAME: ${{ steps.set-vars.outputs.ZONE_NAME }}
       run: |
@@ -142,7 +149,7 @@ runs:
           sleep 1
         done
 
-    - name: Check the SOA SERIAL at the NSD secondary
+    - name: Expect serial 2 of zone ${{ steps.set-vars.outputs.ZONE_NAME }} at the NSD secondary
       env:
         ZONE_NAME: ${{ steps.set-vars.outputs.ZONE_NAME }}
       run: |
@@ -158,21 +165,21 @@ runs:
           sleep 1
         done
 
-    - name: Edit the source zone again and tell Cascade to reload it.
+    - name: Edit and reload serial 3 of zone ${{ steps.set-vars.outputs.ZONE_NAME }}
       env:
         ZONE_NAME: ${{ steps.set-vars.outputs.ZONE_NAME }}
       run: |
         cat >"${ZONE_NAME}zone" <<EOF
         ${ZONE_NAME}          IN SOA ns.${ZONE_NAME} mail.${ZONE_NAME} (
                                      3 60 60 3600 5)
-                               IN NS  NS.${ZONE_NAME}
+                              IN NS  NS.${ZONE_NAME}
         NS.${ZONE_NAME}       IN A   133.69.136.1
         JAIN-BB.${ZONE_NAME}  IN A   133.69.136.3
-                               IN A   192.41.197.2
+                              IN A   192.41.197.2
         EOF
         cascade zone reload ${ZONE_NAME}
 
-    - name: Check zone status
+    - name: Check zone ${{ steps.set-vars.outputs.ZONE_NAME }} status after second reload
       env:
         ZONE_NAME: ${{ steps.set-vars.outputs.ZONE_NAME }}
       run: |
@@ -187,7 +194,7 @@ runs:
           sleep 1
         done
 
-    - name: Check the SOA SERIAL again at the NSD secondary
+    - name: Expect serial 3 of zone ${{ steps.set-vars.outputs.ZONE_NAME }} at the NSD secondary
       env:
         ZONE_NAME: ${{ steps.set-vars.outputs.ZONE_NAME }}
       run: |
@@ -212,15 +219,59 @@ runs:
     # TODO: Verify the AXFR and IXFR response content is as expected /
     # matching that of NSD.
 
-    - run: dig +onesoa +noall +answer @127.0.0.1 -p 4542 ${{ steps.set-vars.outputs.ZONE_NAME }} AXFR > cascade-axfr.log
+    - name: Verify that TSIG is required by Cascade
+      if: ${{ inputs.with-tsig }}
+      env:
+        ZONE_NAME: ${{ steps.set-vars.outputs.ZONE_NAME }}
+      run: |
+        # This should not succeed as it lacks the required TSIG key.
+        # Note that dig will exit with code 0 even if the request fails,
+        # because it considers an error response still to be successful
+        # receipt of a response, so we have to check the actual output.
+        dig @127.0.0.1 -p 4542 ${ZONE_NAME} AXFR &> dig-no-tsig.log
+        if grep -Fq 'Transfer failed' dig-no-tsig.log; then
+          exit 0
+        else
+          echo "::error:: dig unexpectedly was able to AXFR the zone without a TSIG key"
+          exit 1
+        fi
 
-    - run: dig +onesoa +noall +answer @127.0.0.1 -p 4542 ${{ steps.set-vars.outputs.ZONE_NAME }} -t IXFR=1 >cascade-ixfr-1.log
+    - name: Verify Cascade AXFR out
+      env:
+        ZONE_NAME: ${{ steps.set-vars.outputs.ZONE_NAME }}
+      run: |
+        EXTRA_ARGS=
+        if [[ "${{ inputs.with-tsig }}" == "true" ]]; then
+          EXTRA_ARGS="-y ${{ steps.set-vars.outputs.TSIG_SPEC }}"
+        fi
+        echo "EXTRA_ARGS: ${EXTRA_ARGS}"
+        dig +onesoa +noall +answer @127.0.0.1 -p 4542 ${EXTRA_ARGS} ${ZONE_NAME} AXFR &> cascade-axfr.log
+        TEST_DIR="${PWD}/integration-tests/ixfr-out"
+        LC_COLLATE=C sort "${TEST_DIR}/reference-output/${ZONE_NAME}axfr" | egrep -v '^;|^$' > reference.output.sorted
+        LC_COLLATE=C sort cascade-axfr.log > output.sorted
+        diff -u -w output.sorted reference.output.sorted
+
+    - name: Verify Cascade IXFR serial 1..=3 out
+      env:
+        ZONE_NAME: ${{ steps.set-vars.outputs.ZONE_NAME }}
+      run: |
+        EXTRA_ARGS=
+        if [[ "${{ inputs.with-tsig }}" == "true" ]]; then
+          EXTRA_ARGS="-y ${{ steps.set-vars.outputs.TSIG_SPEC }}"
+        fi
+        dig +onesoa +noall +answer @127.0.0.1 -p 4542 ${ZONE_NAME} -t IXFR=1 ${EXTRA_ARGS} &> cascade-ixfr-1-3.log
+        TEST_DIR="${PWD}/integration-tests/ixfr-out"
+        LC_COLLATE=C sort "${TEST_DIR}/reference-output/${ZONE_NAME}ixfr-1-3" | egrep -v '^;|^$' > reference.output.sorted
+        LC_COLLATE=C sort cascade-ixfr-1-3.log > output.sorted
+        diff -u -w output.sorted reference.output.sorted
 
     - run: dig +onesoa +noall +answer @127.0.0.1 -p 4542 ${{ steps.set-vars.outputs.ZONE_NAME }} -t IXFR=2 >cascade-ixfr-2.log
 
     - run: dig +onesoa +noall +answer @127.0.0.1 -p 4542 ${{ steps.set-vars.outputs.ZONE_NAME }} -t IXFR=3 >cascade-ixfr-3.log
 
     - run: dig +onesoa +noall +answer @127.0.0.1 -p 1054 ${{ steps.set-vars.outputs.ZONE_NAME }} AXFR >nsd-axfr.log
+
+    - run: exit 1
 
     - name: Print log files on any failure in this job
       uses: ./.github/actions/print-logfiles
