PoC IXFR-out.
Will need changing based on PR #589.

diff --git a/integration-tests/tests/ixfr-out/action.yml b/integration-tests/tests/ixfr-out/action.yml
--- a/integration-tests/tests/ixfr-out/action.yml
+++ b/integration-tests/tests/ixfr-out/action.yml
@@ -43,11 +43,11 @@ runs:
     - name: Make an initial zone based on RFC 1995 section 7
       run: |
         tee example.test.zone <<'EOF'
-        example.test.       IN SOA ns.example.test. mail.example.test. (
+        EXAMPLE.TEST.       IN SOA NS.EXAMPLE.TEST. mail.example.test. (
                                      1 60 60 3600 5)
-                            IN NS  ns.example.test.
-        ns.example.test.    IN A   133.69.136.1
-        nezu.example.test.  IN A   133.69.136.5
+                            IN NS  NS.EXAMPLE.TEST.
+        NS.EXAMPLE.TEST.    IN A   133.69.136.1
+        NEZU.EXAMPLE.TEST.  IN A   133.69.136.5
         EOF
 
     - name: Add the zone using the custom policy
@@ -81,11 +81,99 @@ runs:
           sleep 1
         done
 
+    - name: Edit the source zone and tell Cascade to reload it.
+      run: |
+        tee example.test.zone <<'EOF'
+        example.test.          IN SOA ns.example.test. mail.example.test. (
+                                     2 60 60 3600 5)
+                               IN NS  NS.EXAMPLE.TEST.
+        NS.EXAMPLE.TEST.       IN A   133.69.136.1
+        JAIN-BB.EXAMPLE.TEST.  IN A   133.69.136.4
+                               IN A   192.41.197.2
+        EOF
+        cascade zone reload example.test
+
+    - name: Check zone status
+      run: |
+        timeout=10 # seconds
+        start=$(date +%s)
+        until cascade zone status example.test | grep -q "Published zone available"; do
+          if (($(date +%s) > (start + timeout))); then
+            cascade zone status example.test
+            echo "timeout: zone status did not report published zone available" >&2
+            exit 1
+          fi
+          sleep 1
+        done
+
+    - name: Check the SOA SERIAL at the NSD secondary
+      run: |
+        timeout=10 # seconds
+        start=$(date +%s)
+        until dig +short @127.0.0.1 -p 1054 example.test SOA | grep -q 'ns.example.test. mail.example.test. 2 60 60 3600 5'; do
+          if (($(date +%s) > (start + timeout))); then
+            cascade zone status example.test
+            dig +short @127.0.0.1 -p 1054 example.test SOA
+            echo "::error:: timeout: NSD did not acquire the zone changes"
+            exit 1
+          fi
+          sleep 1
+        done
+
+    - name: Edit the source zone and tell Cascade to reload it.
+      run: |
+        tee example.test.zone <<'EOF'
+        EXAMPLE.TEST.          IN SOA ns.example.test. mail.example.test. (
+                                     3 60 60 3600 5)
+                               IN NS  NS.EXAMPLE.TEST.
+        NS.EXAMPLE.TEST.       IN A   133.69.136.1
+        JAIN-BB.EXAMPLE.TEST.  IN A   133.69.136.3
+                               IN A   192.41.197.2
+        EOF
+        cascade zone reload example.test
+
+    - name: Check zone status
+      run: |
+        timeout=10 # seconds
+        start=$(date +%s)
+        until cascade zone status example.test | grep -q "Published zone available"; do
+          if (($(date +%s) > (start + timeout))); then
+            cascade zone status example.test
+            echo "timeout: zone status did not report published zone available" >&2
+            exit 1
+          fi
+          sleep 1
+        done
+
+    - name: Check the SOA SERIAL at the NSD secondary
+      run: |
+        timeout=10 # seconds
+        start=$(date +%s)
+        until dig +short @127.0.0.1 -p 1054 example.test SOA | grep -q 'ns.example.test. mail.example.test. 3 60 60 3600 5'; do
+          if (($(date +%s) > (start + timeout))); then
+            cascade zone status example.test
+            dig +short @127.0.0.1 -p 1054 example.test SOA
+            echo "::error:: timeout: NSD did not acquire the zone changes"
+            exit 1
+          fi
+          sleep 1
+        done
+
     # Note: There is no NSD metric that I am aware of that we can use to
     # verify that it received IXFR from Cascade instead of AXFR, nor is there
     # any Cascade Prometheus metric or CLI command that we can use to check
     # this either. Increasing the NSD log level to 9 doesn't cause it to
     # report whether it received IXFR or AXFR either.
+
+    - run: dig +onesoa +noall +answer @127.0.0.1 -p 4542 example.test AXFR
+
+    - run: dig +onesoa +noall +answer @127.0.0.1 -p 4542 example.test -t IXFR=1
+
+    - run: dig +onesoa +noall +answer @127.0.0.1 -p 4542 example.test -t IXFR=2
+
+    - run: dig +onesoa +noall +answer @127.0.0.1 -p 4542 example.test -t IXFR=3
+
+    - run: dig +onesoa +noall +answer @127.0.0.1 -p 1054 example.test AXFR
 
     - name: Print log files on any failure in this job
       uses: ./.github/actions/print-logfiles
