Add the remaining logic based on the original `scripts/tests.sh`.

diff --git a/integration-tests/tests/test-incremental-signing/action.yml b/integration-tests/tests/test-incremental-signing/action.yml
--- a/integration-tests/tests/test-incremental-signing/action.yml
+++ b/integration-tests/tests/test-incremental-signing/action.yml
@@ -68,7 +68,51 @@ runs:
         TEST_DIR="${PWD}/integration-tests/incremental-signing"
         ZONE_FILE="${TEST_DIR}/zones/incremental-signing-test${TEST_IDX}-input1.zone"
         KEY_FILE="${TEST_DIR}/keys/${KEY}"
-        cascade zone add --source "${ZONE_FILE}" --policy "${POLICY}" --import-csk-file "${KEY_FILE}" example
+        cp "${ZONE_FILE}" example.in
+        cascade zone add --source $PWD/example.in --policy "${POLICY}" --import-csk-file "${KEY_FILE}" example
+
+    - name: Wait for the first version to be signed
+      run: |
+        timeout=10 # seconds
+        start=$(date +%s)
+        until dig +short @127.0.0.1 -p 4543 example SOA | grep 12345; do
+          if (($(date +%s) > (start + timeout))); then
+            echo "::error:: timeout: published SOA does not contain 12345"
+            exit 1
+          fi
+          sleep 1
+        done
+
+    - name: Load second version of the zone
+      env:
+        TEST_IDX: "${{ inputs.test_idx }}"
+      run: |
+        TEST_DIR="${PWD}/integration-tests/incremental-signing"
+        ZONE_FILE="${TEST_DIR}/zones/incremental-signing-test${TEST_IDX}-input2.zone"
+        cp "${ZONE_FILE}" example.in
+        cascade zone reload example
+
+    - name: Wait for the second version to be signed
+      run: |
+        timeout=10 # seconds
+        start=$(date +%s)
+        until dig +short @127.0.0.1 -p 4543 example SOA | grep 23456; do
+          if (($(date +%s) > (start + timeout))); then
+            echo "::error:: timeout: published SOA does not contain 23456"
+            exit 1
+          fi
+          sleep 1
+        done
+
+    - name: Compare AXFR output to expected output
+      env:
+        POLICY: "${{ inputs.policy }}"
+        TEST_IDX: "${{ inputs.test_idx }}"
+      run: |
+        TEST_DIR="${PWD}/integration-tests/incremental-signing"
+        cp "${TEST_DIR}/reference-output/incremental-signing-test${TEST_IDX}-input2.zone.${POLICY}.signed.sorted" reference.output.sorted
+        dig @127.0.0.1 -p 4543 example AXFR | egrep -v '^;|^$' | sort -u > output.sorted
+        diff -w -u output.sorted reference.output.sorted
 
     - name: Print log files on any failure in this job
       uses: ./.github/actions/print-logfiles
