More work on the persist-restore system test.

diff --git a/integration-tests/tests/persist-zone/action.yml b/integration-tests/tests/persist-zone/action.yml
--- a/integration-tests/tests/persist-zone/action.yml
+++ b/integration-tests/tests/persist-zone/action.yml
@@ -114,14 +114,6 @@ runs:
         timeout=10 # seconds
         start=$(date +%s)
 
-        # Due to a known issue in Cascade/dnst keyset, currently a second
-        # version of the zone gets signed and published with an incremented
-        # serial number but no other change in the zone. So we have to expect
-        # that.
-        # TODO: Remove this comment and the next line once the issue has been
-        # resolved.
-        let EXPECTED_SERIAL=$(( EXPECTED_SERIAL + 1 ))
-
         until dig +noall +answer @127.0.0.1 -p 4542 example.test AXFR | grep -q "${EXPECTED_SERIAL}" ; do
           if (($(date +%s) > (start + timeout))); then
             echo "::error:: timeout: signed zone did not become available for AXFR with expected SOA '${EXPECTED_SERIAL}'"
@@ -134,18 +126,7 @@ runs:
     - name: Check that Cascade did NOT resign the zone
       run: |
         dig +noall +answer @127.0.0.1 -p 4542 example.test AXFR > example.test.signed2.log
-
-        # Due to a known issue in Cascade/dnst keyset, currently a second
-        # version of the zone gets signed and published with an incremented
-        # serial number but no other change in the zone. So we have to expect
-        # that.
-        # TODO: Remove this comment and the next two lines once the issue has
-        # been resolved.
-        grep -Fv 'SOA' example.test.signed.log > diff-tmp1.log
-        grep -Fv 'SOA' example.test.signed2.log > diff-tmp2.log
-
-        # diff -u example.test.signed.log example.test.signed2.log
-        diff -u diff-tmp1.log diff-tmp2.log
+        diff -u example.test.signed.log example.test.signed2.log
 
     - name: Stop Cascade again
       run: |
@@ -208,14 +189,6 @@ runs:
         start=$(date +%s)
         let EXPECTED_SERIAL=$(( EXPECTED_SERIAL + 1 ))
 
-        # Due to a known issue in Cascade/dnst keyset, currently a second
-        # version of the zone gets signed and published with an incremented
-        # serial number but no other change in the zone. So we have to expect
-        # that.
-        # TODO: Remove this comment and the next line once the issue has been
-        # resolved.
-        let EXPECTED_SERIAL=$(( EXPECTED_SERIAL + 1 ))
-
         until dig +noall +answer @127.0.0.1 -p 4542 example.test AXFR | grep -q "${EXPECTED_SERIAL}" ; do
           if (($(date +%s) > (start + timeout))); then
             echo "::error:: timeout: signed zone did not become available for AXFR with expected SOA '${EXPECTED_SERIAL}'"
@@ -240,9 +213,47 @@ runs:
       run: |
         ZONE_DIR=$(integration-tests/scripts/get-default-path.sh test-env:nameserver-base-dir)
         ZONE_FILE="${ZONE_DIR}/nsd-primary/zones/example.test.primary-zone"
-        perl -pi -e 's/1          ; serial/2          ; serial/' ${ZONE_FILE}
+        perl -pi -e 's/1          ; serial/12345      ; serial/' ${ZONE_FILE}
         perl -pi -e 's/www         A   169.254.1.1/www         A   192.168.0.1/' ${ZONE_FILE}
         ./integration-tests/scripts/manage-test-environment.sh control nsd-primary reload example.test
+
+    - name: Wait for Cascade to load the changed zone
+      run: |
+        timeout=10 # seconds
+        start=$(date +%s)
+
+        until dig +noall +answer @127.0.0.1 -p 4540 example.test SOA | grep -q 12345 ; do
+          if (($(date +%s) > (start + timeout))); then
+            echo "::error:: timeout: signed zone did not become available for AXFR with expected SOA SERIAL 12345"
+            dig +noall +answer @127.0.0.1 -p 4540 example.test SOA
+            exit 1
+          fi
+          sleep 1
+        done
+
+    - name: Wait for Cascade to serve the re-signed zone with a newer serial number
+      env:
+        EXPECTED_SERIAL: ${{ steps.expected-serial.outputs.serial }}
+      run: |
+        timeout=10 # seconds
+        start=$(date +%s)
+        let EXPECTED_SERIAL=$(( EXPECTED_SERIAL + 2 ))
+
+        until dig +noall +answer @127.0.0.1 -p 4542 example.test AXFR | grep -Fq "${EXPECTED_SERIAL}" ; do
+          if (($(date +%s) > (start + timeout))); then
+            echo "::error:: timeout: signed zone did not become available for AXFR with expected SOA '${EXPECTED_SERIAL}'"
+            dig +noall +answer @127.0.0.1 -p 4542 example.test AXFR
+            exit 1
+          fi
+          sleep 1
+        done
+
+    - name: Verify that the modified A record is served in the published zone
+      run: |
+        # Cascade can only answer SOA and XFR queries at the moment so we
+        # cannot query it for the A record we are interested in.
+        dig +noall +answer @127.0.0.1 -p 4542 example.test AXFR > example.test.final.log
+        cat example.test.final.log | grep -Fq www.example.test | grep -Fq "192.168.0.1"
 
     - name: Print log files on any failure in this job
       uses: ./.github/actions/print-logfiles
