Also test partial restoration of a previously signed zone.
As this causes a panic currently.

diff --git a/integration-tests/tests/persist-zone/action.yml b/integration-tests/tests/persist-zone/action.yml
--- a/integration-tests/tests/persist-zone/action.yml
+++ b/integration-tests/tests/persist-zone/action.yml
@@ -31,7 +31,7 @@ runs:
     # 0. Add a zone that cannot be loaded but does not fail `zone add`
     #    immediately so that Cascade has the zone but no content for it,
     #    then stop Cascade and restart it, to verify that Cascade can handle
-    #    restoration without any persisted state to restore from.
+    #    restoration without any persisted state paths to restore from.
     # ------------------------------------------------------------------------
 
     - name: Add a non-existing upstream zone
@@ -203,11 +203,9 @@ runs:
         diff -u example.test.signed.log example.test.signed2.log
 
     # ------------------------------------------------------------------------
-    # 3. Stop and restart Cascade again so we can test that it:
-    #      - If persisted state files are deleted, does Cascade handle this
-    #        correctly? It should attempt to load the persisted data files (as
-    #        has paths to them in its main state file), find that they are
-    #        missing and then ignore them and fully re-sign the zone.
+    # 3. Delete all persisted zone data files to verify that Cascade can
+    #    handle restoration with persisted state paths that refer to missing
+    #    files.
     # ------------------------------------------------------------------------
 
     - name: Stop Cascade again
@@ -597,6 +595,92 @@ runs:
         dig +noall +answer @127.0.0.1 -p 4542 -t ixfr=${CLIENT_SERIAL} example.test > "${OUT_FILE}"
         sed -e 's/\s\+/ /g' "${OUT_FILE}" | grep -F '5 IN SOA' > diff.in
         diff -u diff.in "${EXPECTED_OUT_FILE}"
+
+    # ------------------------------------------------------------------------
+    # 7. Delete all persisted signed zone data files to verify that Cascade
+    #    can handle partial restoration for a zone that was previously signed
+    #    at least once.
+    # ------------------------------------------------------------------------
+
+    - name: Stop Cascade again
+      run: |
+        pkill cascaded
+
+    - name: Wait for Cascade to exit again
+      run: |
+        timeout=10 # seconds
+        start=$(date +%s)
+        until ! cascade health; do
+          if (($(date +%s) > (start + timeout))); then
+            cascade health
+            echo "::error:: timeout: health check did not indicate Cascade had stopped"
+            exit 1
+          fi
+          sleep 1
+        done
+
+    - name: Delete the persisted signed zone data that Cascade wrote to disk
+      run: |
+        CASCADE_DIR=${{ github.workspace }}/cascade-dir
+        rm "${CASCADE_DIR}"/zone-state/example.test.signed.*
+
+    - name: Start Cascade again
+      run: |
+        CASCADE_DIR=${{ github.workspace }}/cascade-dir
+        cascaded --config "${CASCADE_DIR}/config.toml" --state "${CASCADE_DIR}/state.db" --daemonize &>"${CASCADE_DIR}/cascade-startup.log"      
+
+    - name: Wait for Cascade to become healthy again
+      run: |
+        timeout=10 # seconds
+        start=$(date +%s)
+        until cascade health; do
+          if (($(date +%s) > (start + timeout))); then
+            echo "::error:: timeout: health check did not indicate Cascade had started"
+            exit 1
+          fi
+          sleep 1
+        done
+
+    - name: Check that Cascade still knows the zone
+      run: |
+        timeout=10 # seconds
+        start=$(date +%s)
+        until cascade zone list | grep -q example.test; do
+          if (($(date +%s) > (start + timeout))); then
+            cascade zone list
+            echo "::error:: timeout: Cascade no longer knows the zone"
+            exit 1
+          fi
+          sleep 1
+        done
+
+    - name: Wait for Cascade to serve the re-signed zone with a newer serial number
+      env:
+        EXPECTED_SERIAL: ${{ steps.expected-serial.outputs.serial }}
+      run: |
+        timeout=10 # seconds
+        start=$(date +%s)
+        let EXPECTED_SERIAL=$(( EXPECTED_SERIAL + 3 ))
+
+        until dig +noall +answer @127.0.0.1 -p 4542 example.test AXFR | grep -q "${EXPECTED_SERIAL}" ; do
+          if (($(date +%s) > (start + timeout))); then
+            echo "::error:: timeout: signed zone did not become available for AXFR with expected SOA '${EXPECTED_SERIAL}'"
+            dig +noall +answer @127.0.0.1 -p 4542 example.test AXFR
+            exit 1
+          fi
+          sleep 1
+        done
+
+    - name: Save the signed zone for later comparison
+      run: |
+        dig +noall +answer @127.0.0.1 -p 4542 example.test AXFR > example.test.signed7.log
+
+    - name: Check that Cascade DID resign the zone, not just bump the serial number
+      run: |
+        if diff -u example.test.signed2.log example.test.signed7.log > unexpected-diff.log; then
+          echo "::error:: Cascade should have re-signed the zone"
+          exit 1
+        fi
 
     - name: Print log files on any failure in this job
       uses: ./.github/actions/print-logfiles
