Review feedback: Don't wait 10 seconds, detect the XFR failure ASAP.

diff --git a/integration-tests/tests/upstream-tsig/action.yml b/integration-tests/tests/upstream-tsig/action.yml
--- a/integration-tests/tests/upstream-tsig/action.yml
+++ b/integration-tests/tests/upstream-tsig/action.yml
@@ -42,14 +42,19 @@ runs:
       run: |
         timeout=10 # seconds
         start=$(date +%s)
-        until cascade zone status example-tsig.test | grep -q "Published zone available"; do
+
+        # TODO: The error message we are checking for is the one that Cascade
+        # currently produces, but doesn't seem like the correct error...
+        # See: https://github.com/NLnetLabs/cascade/issues/603
+        until cascade zone status example-tsig.test | grep -q "ERROR: the AXFR failed: the server's response was semantically incorrect: Not a valid XFR response"; do
           if (($(date +%s) > (start + timeout))); then
-            exit 0
+            echo "::error:: zone status failed to report the expected error"
+            cascade zone status example-tsig.test
+            exit 1
           fi
           sleep 1
         done
-        echo "::error:: zone status unexpectedly reports TSIG required zone was retrieved and published without using the TSIG key"
-        exit 1
+        exit 0
 
     - name: Remove and re-add the zone with the required TSIG key.
       run: |
